import Head from 'next/head';
import { useAuthor } from '@/AuthorContext';
import Card from '@/components/Card';
import { useState } from 'react';
import CardSkeleton from '@/components/Skeletons/CardSkeleton';
import EmptyBoard from '@/components/EmptyBoard';

export default function Home(props) {
  const { setAuthor, booksIndex, loading } = useAuthor();
  const [searchAuthor, setSearchAuthor] = useState();

  const handleSubmit = () => {
    setAuthor(searchAuthor);
  };
  return (
    <>
      <Head>
        <title>Before Sunset</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main-content">
        <div className="logo-header">
          <img src="logo.png" alt="logo" />
        </div>
        <div className="search-container">
          <h2 className="search-container__title">Lorem Board</h2>
          <span className="search-container__input">
            <p>books of</p>
            <input onChange={(e) => setSearchAuthor(e.target.value)} />
          </span>
          <button className="search-container__button" onClick={handleSubmit}>
            submit
          </button>
        </div>
        <div className="board">
          {loading
            ? Array.from({ length: 10 }, (_, index) => index + 1).map((i) => <CardSkeleton key={i} />)
            : booksIndex &&
              Object.keys(booksIndex).length > 0 &&
              Object.keys(booksIndex)?.map((i, index) => <Card key={i} year={i} data={booksIndex[i]} />)}
        </div>
        <div className="empty-board-container">
          {!loading && booksIndex && Object.keys(booksIndex).length === 0 && <EmptyBoard />}
        </div>
      </div>
    </>
  );
}
